# Generated by Django 5.1.4 on 2024-12-27 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'Удобство', 'verbose_name_plural': 'Удобства'},
        ),
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='apartmentamenity',
            options={'verbose_name': 'Удобство в квартире', 'verbose_name_plural': 'Удобства в квартирах'},
        ),
        migrations.AlterModelOptions(
            name='apartmentimage',
            options={'verbose_name': 'Фото квартиры', 'verbose_name_plural': 'Фото квартир'},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Здание', 'verbose_name_plural': 'Здания'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Бронирование по дням', 'verbose_name_plural': 'Бронирования по дням'},
        ),
        migrations.AlterModelOptions(
            name='residentialcomplex',
            options={'verbose_name': 'Жилой комплекс', 'verbose_name_plural': 'Жилые комплексы'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.CreateModel(
            name='ReservationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало бронирования')),
                ('end_date', models.DateField(verbose_name='Окончание бронирования')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_groups', to='main.apartment', verbose_name='Квартира')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.reservationgroup', verbose_name='Бронирование'),
        ),
    ]
